services:
  - type: web
    name: stockastic-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    numPorts: 1
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d8k072a8qa3s73bd588g-a.oregon-postgres.render.com:5432/stockastic_db?currentSchema=public
      - key: SPRING_DATASOURCE_USERNAME
        value: stockastic_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: mqi4pNFlfgThTb5kutafU7NthPP8ZSLW
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_AI_CHAT_MODEL
        value: none
      - key: EUREKA_CLIENT_ENABLED
        value: false
